#!/usr/bin/env bash

curl -C - -L -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

cat <<-CHROME | sudo tee /usr/bin/chrome
#!/usr/bin/env bash
google-chrome "\$@"
CHROME

cat <<-INCOGNITO | sudo tee /usr/bin/porn-mode
#!/usr/bin/env bash
google-chrome --incognito "\$@"
INCOGNITO

sudo chmod +x /usr/bin/chrome /usr/bin/porn-mode

