#!/usr/bin/env bash

sudo wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | apt-key add -
echo "deb http://download.virtualbox.org/virtualbox/debian stretch contrib non-free" | sudo tee virtualbox.list
sudo mv virtualbox.list /etc/apt/sources.list.d/

:sudo wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | apt-key add -
sudo wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add -

sudo apt-get update
sudo apt-get -y install dkms virtualbox-5.0

