#!/bin/bash

abs_val=$(echo $1 | /bin/grep -Po "\d+")
sign=$(echo $1 | /bin/grep -o "-")
[[ -z "$sign" ]] && sign="+"

# get the backlight handler
handler=/sys/class/backlight/intel_backlight

# get current brightness
old_brightness=$(cat $handler/brightness)

# get max brightness
max_brightness=$(cat $handler/max_brightness)
delta=$(echo "scale=0; $max_brightness * $abs_val / 100"  | bc -l)

# calculate new brightness %
new_brightness=$(($old_brightness $sign $delta))

# calculate new brightness value
#new_brightness=$(( $max_brightness * $new_brightness_p / 100 ))

[[ $((new_brightness)) -gt $((max_brightness)) ]] && new_brightness=$max_brightness
[[ $((new_brightness)) -lt 0 ]] && new_brightness=100

# set the new brightness value
echo $new_brightness > $handler/brightness

