#!/bin/bash

abs_val=$(echo $1 | /bin/grep -Po "\d+")
sign=$(echo $1 | /bin/grep -o "-")
[[ -z "$sign" ]] && sign="+"
# base dir for backlight class
basedir="/sys/class/backlight/"

# get the backlight handler
handler=$basedir$(/bin/ls $basedir)"/"

# get current brightness
old_brightness=$(/bin/cat $handler"brightness")

# get max brightness
max_brightness=$(/bin/cat $handler"max_brightness")
delta=$(echo "scale=0; $max_brightness * $abs_val / 100"  | /usr/bin/bc -l)

# calculate new brightness %
new_brightness=$(($old_brightness $sign$delta))

# calculate new brightness value
#new_brightness=$(( $max_brightness * $new_brightness_p / 100 ))

[[ $((new_brightness)) -gt $((max_brightness)) ]] && new_brightness=$max_brightness
[[ $((new_brightness)) -lt 0 ]] && new_brightness=100

# set the new brightness value
su -c "/bin/chmod 666 ${handler}brightness"
/bin/echo $new_brightness > ${handler}brightness
