#!/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  sudo systemctl stop bluetooth
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  sudo systemctl start bluetooth
fi

STATUS=$(systemctl status bluetooth | grep -o 'active (running)')

if [[ ! -z "${STATUS}" ]]; then
  echo "on"
  echo "on"
  echo "#0000ff"
else
  echo "off"
  echo "off"
  echo "#ffff00"
fi
