#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  ufw enable
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  ufw reload
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  ufw disable
fi

status=$(ufw status 2>/dev/null)

if [[ $? -gt 0 ]]; then
  exit
fi

if [[ "${status}" != *inactive* ]]; then
  echo "on"
  echo "on"
  echo ""
else
  echo "off"
  echo "off"
  echo ""
fi
