#!/usr/bin/env bash

URGENT_VALUE=25
APT_LIST=$(sudo apt update -qq  &> /dev/null && apt list --upgradable 2>/dev/null | wc -l)
PACKAGE_COUNT=$((APT_LIST-1))

if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo "${PACKAGE_COUNT}" # full-text
  echo "${PACKAGE_COUNT}" # short-text
  echo ""
  if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
    exit 33
  fi
fi
