#!/bin/bash

if [[ -c /dev/video0 ]]; then
  if [[ "$(fuser /dev/video0)" != "" ]]; then
    echo "rec"
    echo "rec"
    echo "#ff0000"
  else
    echo "standby"
    echo "standby"
    echo ""
  fi
else
  echo "off"
  echo "off"
  echo "#ffff00"
fi
