#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="${1}"
ALERT_LOW="${2:-10}" # color will turn red under this value (default: 10%)

disk=$(df -h -P "$DIR" | tail -1)
free=$(echo "$disk" | awk '{print $4}')
used=$(echo "$disk" | awk '{print $5}' | grep -Po "\d+")
[[ $((100-$used)) -lt $((ALERT_LOW)) ]] && ALERT="$(tput setaf 1)!!"
echo "${ALERT}${free}$(tput sgr0)"
