#!/bin/bash

iface=$1

SSID="$(sudo iw $iface link | grep -Po "(?<=SSID: ).*")"
BITRATE="$(sudo iw $iface link | grep -Po "(?<=tx bitrate: ).*" )"
SIGNAL="$(sudo iw $iface link | grep -Po "(?<=signal: ).*")"
if [[ -z "$SSID" ]]; then
  echo " wlan down"
else
  printf " %s %13s (%8s)"  "$SSID" "$BITRATE" "$SIGNAL"
fi
